//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenzat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int ID { get; set; }
        public Nullable<int> ListID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Drawable { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string MoreText { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual List List { get; set; }
    }
}
