//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenzat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public List()
        {
            this.ListItems = new HashSet<ListItem>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> ListDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> FbShares { get; set; }
        public Nullable<int> TwitterShares { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Hot { get; set; }
        public Nullable<int> ListType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Tag { get; set; }
    
        public virtual ICollection<ListItem> ListItems { get; set; }
        public virtual Moderator Moderator { get; set; }
    }
}
