//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenzat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public Moderator()
        {
            this.Lists = new HashSet<List>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public Nullable<bool> CreateAdmin { get; set; }
        public Nullable<bool> CreateList { get; set; }
        public Nullable<bool> SetHotLists { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> ApproveLists { get; set; }
    
        public virtual ICollection<List> Lists { get; set; }
    }
}
